apiVersion: kubedb.com/v1alpha1
kind: Snapshot
metadata:
  name: p1-xyz
  namespace: demo
  labels:
    kubedb.com/kind: Postgres
spec:
  databaseName: p1
  storageSecretName: s3-secret
  s3:
    endpoint: 's3.amazonaws.com'
    bucket: kubedb
