apiVersion: kubedb.com/v1alpha1
kind: Snapshot
metadata:
  name: e1-xyz
  namespace: demo
  labels:
    kubedb.com/kind: Elasticsearch
spec:
  databaseName: e1
  storageSecretName: snap-secret
  s3:
    endpoint: 's3.amazonaws.com'
    bucket: kubedb
