apiVersion: kubedb.com/v1alpha1
kind: Elasticsearch
metadata:
  name: e1
  namespace: demo
spec:
  version: 5.6.3
  replicas: 1
  doNotPause: false
  storage:
    resources:
      requests:
        storage: 50Mi
